CREATE DATABASE IF NOT EXISTS rosdb
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE rosdb;

CREATE TABLE IF NOT EXISTS turtlepos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  x DOUBLE NOT NULL,
  y DOUBLE NOT NULL,
  theta DOUBLE NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
